Shows without a status need an empty string set
Sonarr errors out when adding a show without a "status" (status is null), setting the status to empty fixes this issue as Sonarr uses StringComparsion as shown here https://github.com/Sonarr/Sonarr/blob/816cf608fcef07e375aa750a863d0a7365108981/src/NzbDrone.Core/MetadataSource/SkyHook/SkyHookProxy.cs#L217. 

```
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSeriesStatus (System.String status) [0x00000] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:217 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSeries (NzbDrone.Core.MetadataSource.SkyHook.Resource.ShowResource show) [0x00150] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:147 
  at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () <0x4027af00 + 0x001a5> in <filename unknown>:0 
  at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x7f041fb43cb0 + 0x001fb> in <filename unknown>:0 
  at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x401f02d0 + 0x00070> in <filename unknown>:0 
  at NzbDrone.Common.Extensions.EnumerableExtensions.SelectList[TSource,TResult] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Extensions\IEnumerableExtensions.cs:81 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewSeries (System.String title) [0x000df] in M:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:94 
```